# Generated by Django 4.0 on 2021-12-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('U_profile_pic', models.ImageField(upload_to='pics')),
                ('U_main_pic', models.ImageField(upload_to='pics')),
                ('caption', models.TextField()),
            ],
        ),
    ]
