# Generated by Django 4.0 on 2021-12-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_uploads',
            name='comments',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
